export default {
    MARK_NOTIFICATION_AS_READ_BY_ID: 'MARK_NOTIFICATION_AS_READ_BY_ID',
    MARK_NOTIFICATION_AS_UNREAD_BY_ID: 'MARK_NOTIFICATION_AS_UNREAD_BY_ID',
    MARK_NOTIFICATION_AS_READ: 'MARK_NOTIFICATION_AS_READ',
    START_NOTIFICATION_READ: 'START_NOTIFICATION_READ',
    FINISH_NOTIFICATION_READ: 'FINISH_NOTIFICATION_READ',
    START_NOTIFICATION_FETCH: 'START_NOTIFICATION_FETCH',
    START_LOGIN: 'START_LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',
    CHANGE_AVATAR: 'CHANGE_AVATAR'
}